### PR TITLE
fix(shared-link-settings-modal): Update custom URL label

### PR DESCRIPTION
**Pull request by tjgupta**
Update section heading and form label for custom URLs in shared link settings modal.

Screen Shot 2019-04-08 at 1 15 04 PM

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @tjgupta has signed the CLA. Thanks for the pull request!

**Comment by prakash-kumar** [comment]
is this the final copy @tjgupta ? did Morgan ok this?

**Comment by tjgupta** [comment]
Yep, that's the final copy for now. :)

**Pull request merged**
