### PR TITLE
New: box-react-ui upgrade script

### PR DESCRIPTION
**Pull request by pramodsum**
- Automates upgrading of box-react-ui inside the repository

### CODE REVIEW

**Comment by boxcla** [comment]
# Webpack Bundle Size Github Bot

| Bundle        | Diff | Percentage Diff | Before | After |
| ------------- |:----:|:---------------:|:------:|:-----:|
| Total | 0 B | 0.00% | 0 B | 0 B |

Compared against previously merged PR #256

**Powered by [webpack-bundle-size-github-bot](https://github.com/wenboyu2/webpack-bundle-size-github-bot/)**

**Comment by pramodsum** [comment]
This script won't merge the change automatically. It will create a commit and push it your fork. You still have to manually create a PR and merge that in

**Comment by priyajeet** [comment]
I don't think we need any script for this. Since this should ideally be done as part of any other commit that requires an upgrade. We will not be doing any upgrades on its own.

**Comment by jeremypress** [comment]
@priyajeet I agree that it shouldn't be a part of the release process, but it doesn't hurt to have a script that makes upgrading BRUI easier.

**Comment by pramodsum** [comment]
I didn't include this as a part of the release process. It's more an optional script to run if we need to upgrade BRUI

**Comment by priyajeet** [comment]
I do not want additional scripts added unless they are really necessary. This one doesn't seem necessary as the same can be accomplished by just running `yarn upgrade-interactive --latest` or `yarn upgrade box-react-ui` or `yarn add box-react-ui@VERSION --peer/dev`. If at all, you should just have the command directly inside package.json scripts section without a shell script.

Should not be adding unnecessary things to maintain. And box-react-ui is a 3rd party dep like React or React-dom etc. We aren't adding scripts for them, so should not add for box-react-ui either.

**Pull request closed without merging**
