### PR TITLE
feat: add rowHeight prop to ContentExplorerModal

### PR DESCRIPTION
**Pull request by apieceofbart**
Adding rowHeight prop to ContentExplorerModal component so we could customize the row height in admin-console ui.

### CODE REVIEW

**Review by SkyisAakash — DISMISSED** [review]

**Review by greg-in-a-box — CHANGES_REQUESTED** [review]
nit: I noticed its alphabetize in one of the spots you changed.  Can we alphabetize the rest?

**Comment by apieceofbart** [comment]
> nit: I noticed its alphabetize in one of the spots you changed. Can we alphabetize the rest?

Uhmm no? In 2022 this should be automated.

**Comment by QingyuChai** [comment]
> > nit: I noticed its alphabetize in one of the spots you changed. Can we alphabetize the rest?
> 
> Uhmm no? In 2022 this should be automated.

We're currently working on adding enforced/automatic sorting

**Comment by apieceofbart** [comment]
> > > nit: I noticed its alphabetize in one of the spots you changed. Can we alphabetize the rest?
> > 
> > 
> > Uhmm no? In 2022 this should be automated.
> 
> We're currently working on adding enforced/automatic sorting

That's good to hear. I don't mind doing the manual work but I think it's pointless if it's not enforced since the next person will come and add a prop to the end of the list

**Review by tjuanitas — APPROVED** [review]
lgtm

**Review by tjuanitas — APPROVED** [review]

**Review by greg-in-a-box — APPROVED** [review]

**Pull request merged**
