### PR TITLE
build: Prefix scripts with yarn to enforce local binary usage

### PR DESCRIPTION
**Pull request by jstoffan**
Yarn all the things.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jstoffan has signed the CLA. Thanks for the pull request!

**Comment by alexkrolick** [comment]
Isn't that the default?

**Comment by jstoffan** [comment]
Hmm. The binary path shown in the console output is different with/without this change. Let me install eslint globally and check the versions.

**Comment by jstoffan** [comment]
Looks like you're right @alexkrolick. The path in the console shows `eslint` without this change, but it's still the local binary, even if you have it installed globally as well. My bad!

**Pull request closed without merging**
