### PR TITLE
Chore: Remove custom scrollbar styles

### PR DESCRIPTION
**Pull request by jeremypress**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jeremypress has signed the CLA. Thanks for the pull request!

**Comment by boxcla** [comment]
# Webpack Bundle Size Github Bot

| Bundle        | Diff | Percentage Diff | Before | After |
| ------------- |:----:|:---------------:|:------:|:-----:|
| Total | 0 B | 0.00% | 0 B | 0 B |

Compared against previously merged PR #452

**Powered by [webpack-bundle-size-github-bot](https://github.com/wenboyu2/webpack-bundle-size-github-bot/)**

**Comment by jeremypress** [comment]
@priyajeet keeping it easier to maintain for now, Skills looked ok to me but if there's an ask to go back I can override the custom styles to keep preview normal.

**Comment by priyajeet** [comment]
@jeremypress can you post an image how transcripts look like?

**Pull request merged**
