### PR TITLE
fix(datepicker): Pass user timeZone from INTL for formatDate 

### PR DESCRIPTION
**Pull request by SkyisAakash**

### CODE REVIEW

**Comment by SkyisAakash** [comment]
Screen Shot 2022-04-14 at 3 42 24 PM

**Review by tjuanitas — COMMENTED** [review]
Hi Aakash, can you update the PR title and commit message to have a description of the change?

This has some examples:
https://github.com/box/box-ui-elements/blob/master/CONTRIBUTING.md#step-4-push-your-feature-branch-to-your-fork

**Comment by SkyisAakash** [comment]
> Hi Aakash, can you update the PR title and commit message to have a description of the change?
> 
> This has some examples: https://github.com/box/box-ui-elements/blob/master/CONTRIBUTING.md#step-4-push-your-feature-branch-to-your-fork

Updated.

**Review by tjuanitas — APPROVED** [review]

**Comment by tjuanitas** [comment]
Force merging since Semantic Pull Request is down and passes other checks.

**Pull request merged**
