### PR TITLE
feat(unified-share-modal): remove beta badge from USM

### PR DESCRIPTION
**Pull request by booc0mtaco**
Update tests, components, and imports to no longer render this badge.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @booc0mtaco has signed the CLA. Thanks for the pull request!

**Comment by priyajeet** [comment]
feat(unified-share-modal)

**Comment by priyajeet** [comment]
BTW, is usm becoming the default? And if so, can we nuke the older versions?

**Comment by booc0mtaco** [comment]
@priyajeet Is there documentation for what scope names are preferred? one rule could be that it should make the component's folder name when specified. 

I think this unified one will eventually be the only one available. I don't suppose we would have to worry about this being used since there was no interface for seeing it until recently. Once notes has this modal, it should be safe to remove the others

**Comment by priyajeet** [comment]
Yeah thats what I was thinking, just use the folder name.

**Comment by booc0mtaco** [comment]
Reminder to update scope on squash and merge as titles aren't reused for merged commits

**Pull request merged**
