### PR TITLE
fix(grid-view): unhide focus outline for grid view slider

### PR DESCRIPTION
**Pull request by QingyuChai**
Remove styles that hide focus outline. Not sure why it was hidden in the first place, it doesn't show up with mouse interaction.

Initially introduced here: https://github.com/box/box-ui-elements/commit/ef4a7ee68ca1b2e2d0eb3410a05c1e66fc5dceb6

Before:
https://user-images.githubusercontent.com/24941488/212198025-651b4076-73f3-4000-be5d-c4f9a0baa50f.mov

After:
https://user-images.githubusercontent.com/24941488/212197943-ccb3473d-8f81-426e-9cfb-a094eab9619e.mov

### CODE REVIEW

**Review by benjamin-shen — APPROVED** [review]
> Not sure why it was hidden in the first place

Interesting, maybe you could check the git blame to see if there was any reason?

**Comment by QingyuChai** [comment]
Yeah, not sure why that person added the outline: none

**Review by tjuanitas — APPROVED** [review]

**Comment by tjuanitas** [comment]
> > Not sure why it was hidden in the first place
> 
> Interesting, maybe you could check the git blame to see if there was any reason?

looks like the component was originally copied from EUA

**Comment by QingyuChai** [comment]
works as expected on firefox as well - gonna proceed with merging!

**Comment by QingyuChai** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring

**Pull request merged**
