### PR TITLE
fix(nudge): update css height property

### PR DESCRIPTION
**Pull request by laughnan**
Screen Shot 2020-02-08 at 23 36 24

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @laughnan has signed the CLA. Thanks for the pull request!

**Comment by jstoffan** [comment]
Seems like this should be a `fix` rather than a `chore`.

**Comment by sahiga** [comment]
@laughnan Does the `Nudge` visual regression test snapshot need to be updated?

**Comment by laughnan** [comment]
@sahiga nope! the existing snapshot has content greater than 450 pixels (i checked).

**Pull request merged**
