### PR TITLE
fix: disable copy in textInputWithCopyButton when button is disabled

### PR DESCRIPTION
**Pull request by kdesai-box**
Currently textInputWithCopyButton allows the user to use ctrl c to copy the text input even when button is disabled. This change adds a disableCopy prop that will completely disable the ability to copy when set to true.

### CODE REVIEW

**Comment by tjuanitas** [comment]
hi @kdesai-box!

does the `disabled` prop not work for this use case? https://github.com/box/box-ui-elements/blob/master/src/components/text-input-with-copy-button/TextInputWithCopyButton.js#L29

Screenshot 2023-09-29 at 4 49 17 PM

btw the blueprint team is happy to work with you if you're interested in a blueprint equivalent

**Comment by kdesai-box** [comment]
hi @tjuanitas 
I was advised not to use the disabled prop to fix this ctrl c bug, however it seems to work fine and pass all tests!

**Review by tjuanitas — COMMENTED** [review]
interesting bug! I didn't realize that a `div` could have an `onCopy` event. one minor comment but cool find 👍 

> I was advised not to use the disabled prop to fix this ctrl c bug

any particular reason not to? maybe it's still a valid concern

**Comment by kdesai-box** [comment]
> interesting bug! I didn't realize that a `div` could have an `onCopy` event. one minor comment but cool find 👍
> 
> > I was advised not to use the disabled prop to fix this ctrl c bug
> 
> any particular reason not to? maybe it's still a valid concern

We weren't sure how this would effect other projects using this particular button and thought it best to just create a new prop for our specific use. However, now that I look at it again if the intent is that the button should be completely disabled its probably best to use the original disable prop.

**Review by tjuanitas — APPROVED** [review]
lgtm! I would update the PR title and use `fix` instead of `feat` now

also the repo requires two approvals, if you have a teammate already part of the public Box org they can review

**Review by jsenar — APPROVED** [review]
lgtm

**Pull request merged**
