### PR TITLE
chore(bdl-colors): add script to detect and convert non-BDL color values

### PR DESCRIPTION
**Pull request by booc0mtaco**
Adding better script to help detect and replace obsolete colors in JS and SCSS files. *note*: postponing using a CLI parser for now

```
Usage: bdlColorManager operation fileName [--verbose]

Supported operations:
        check           check to see if a file contains deprecated values (returns error if it does)
        swap            replace known-deprecated variable names in a JS or SCSS file
```

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @booc0mtaco has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
I attempted to write in a way so we could potentially incorporate into our linter or elsewhere (a prelude to fully deprecating the old values)

**Comment by booc0mtaco** [comment]
Need to add a few pieces I missed for one use case

**Comment by booc0mtaco** [comment]
@jstoffan can you re-review, please? I forgot a few pieces to handle SCSS, so added those in.

**Pull request merged**
