### PR TITLE
ci(i18n): update translations

### PR DESCRIPTION
**Pull request by boxmoji**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @boxmoji has signed the CLA. Thanks for the pull request!

**Comment by ellia99** [comment]
[Obat Aborsi Asli](https://github.com/piielcytotec/klinik-larista/commit/7d8a0b18157f31e30e46b989763bf70830c3d371#commitcomment-32565941)

[Obat Telat Datang Bulan](https://github.com/piielcytotec/klinik-larista/commit/7d8a0b18157f31e30e46b989763bf70830c3d371#commitcomment-32565941)

**Pull request merged**
