### PR TITLE
chore(unified-share-modal): update copy for ftux

### PR DESCRIPTION
**Pull request by prakash-kumar**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @prakash-kumar has signed the CLA. Thanks for the pull request!

**Comment by prakash-kumar** [comment]
Screen Shot 2019-03-12 at 5 05 53 PM

**Comment by booc0mtaco** [comment]
Should update link with underline

**Comment by prakash-kumar** [comment]
Screen Shot 2019-03-12 at 5 14 06 PM

**Pull request merged**
