### PR TITLE
fix(unified-share-modal): move shared link toggle tooltip to middle left

### PR DESCRIPTION
**Pull request by ittaishay**
avoids overlapping other elements in USM

Screen Shot 2019-04-03 at 6 39 37 PM

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @ittaishay has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
Does this only apply to an FTUX modal in the unified share modal?

**Comment by ittaishay** [comment]
> Does this only apply to an FTUX tooltip in the unified share modal?

@booc0mtaco yup, one that I added about a week ago

**Pull request merged**
