### PR TITLE
Fix: Remove upload progress bar when item is pending

### LINKED ISSUE #226: Content Uploader progress indicator is confusing
We are using the Box Content Uploader in one of our web applications, and several of our users are telling us it does not work, saying the upload progress is always stuck at zero.

This happens because although it appears that uploading has begun, since the progress indicator is displayed once a file is selected or dropped in, they have not actually pressed the upload button yet.

screen shot 2018-03-15 at 10 19 15 am

### PR DESCRIPTION
**Pull request by tonyjin**
Fixes #226.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @tonyjin has signed the CLA. Thanks for the pull request!

**Comment by tonyjin** [comment]
@wenboyu2 should be straight-forward but wanted your quick approval to see if this affects the UploadsManager use case.

**Comment by wenboyu2** [comment]
# Webpack Bundle Size Github Bot

| Bundle        | Diff | Before | After |
| ------------- |:----:|:------:|:-----:|
| Total | 0 B | 0 B | 0 B |

Compared against previously merged PR #252

**Powered by [webpack-bundle-size-github-bot](https://github.com/wenboyu2/webpack-bundle-size-github-bot/)**

**Comment by tonyjin** [comment]
@jeremypress I'm going to merge this in as-is. Snapshot testing didn't work in when I tried it for 5 minutes. I'll add a separate task for slowly adding snapshot testing to this code base.

**Pull request merged**
