### PR TITLE
feat(content-sharing): Launch ContentSharing from a custom button

### PR DESCRIPTION
**Pull request by sahiga**
This PR adds a `ContentSharingLauncher` component that instantiates `ContentSharing` as a form within the containing page or as a modal on button click, depending on the presence of the optional `customButton` property.

content-sharing-launch-button

### CODE REVIEW

**Comment by manishPh** [comment]
Question: What is the top level component for this element? Is it `<ContentSharingLauncher />` or `<ContentSharing.js />`. Or it depends upon use-cases?

**Comment by sahiga** [comment]
Good question, @manishPh. The top level is `ContentSharingLauncher`, as that's where the API is initialized. Would you recommend renaming these components to clarify the hierarchy?

**Comment by manishPh** [comment]
@sahiga yeah, I would keep `<ContentSharing />` as the top level element, consistent with other elements.

**Comment by sahiga** [comment]
@manishPh Fixed. The diff looks big, but I mostly just renamed ContentSharingLauncher -> ContentSharing and ContentSharing -> SharingModal. The actual changes to SharingModal (the old ContentSharing component) can be found in the first commit: https://github.com/box/box-ui-elements/pull/2266/commits/a6664f9e8a9a78d7f628c8320a67891b25eb1ce2

**Pull request merged**
