### PR TITLE
 chore(unified-share-modal): Update shared link call to action strings

### PR DESCRIPTION
**Pull request by shahzadaziz**
Changes in this PR include: 
- Update `linkShareOn` and `linkShareOff` strings for shared link toggle in unified share modal. 
- Add CSS to show pointer cursor on shared link toggle label.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @shahzadaziz has signed the CLA. Thanks for the pull request!

**Comment by priyajeet** [comment]
Please add a descriptive message to the PR. CTA =???

**Pull request merged**
