### PR TITLE
Avatar "ghost" loading state

### PR DESCRIPTION
**Pull request by alexkrolick**
- a45a1b833e2458b317e762922fefddb04b1ccdc2 memoize call to get authenticated avatar url
- 16cb9f7e405b9564a5668f08bda007e748a2523e add ghost loading state to avatars with urls (most have a url since the auth call doesn't check for existence at the same time)

<details>
<summary>No url (straight to initials)</summary>

Kapture 2019-04-08 at 17 56 45

</details>

<details>
<summary>Has url (loads async)</summary>

Kapture 2019-04-08 at 17 52 36

</details>

<details>
<summary>Url errors out (fades to initials)</summary>

Kapture 2019-04-08 at 17 42 16

</details>

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @alexkrolick has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
Should be possible to load the avatars with images such that they also fade in. For instance, once resolved, it'd add the image in a new container with opacity 0, then set a class such that it transitions in. (would treat this is a separate bit of work to be more iterative.)

**Comment by alexkrolick** [comment]
I'd like to do add the image fade in effect as well, but there is no onload event for img tags - it uses onerror to trigger the fallback to initials at the moment. Might be able to come up with something later but this seemed like an improvement.

**Comment by alexkrolick** [comment]
Superseded by https://github.com/box/box-ui-elements/pull/1076

**Pull request closed without merging**
