### PR TITLE
test(access-stats): update mocks to avoid invariant errors in test

### PR DESCRIPTION
**Pull request by booc0mtaco**
This fixes snapshots where it referenced a non-existant component name and resolved to `undefined`

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @booc0mtaco has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
Example:

```console
      Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

**Comment by booc0mtaco** [comment]
One improvement will be to handle prop types passed in to the mocked i18n components for verification. This will require many more snapshot changes and some refactoring, so will break this out as a separate task

**Pull request merged**
