### PR TITLE
docs(assets): add auto-generated documentation to icons/illustrations

### PR DESCRIPTION
**Pull request by booc0mtaco**
This includes link to issue ticket creation to aid in future improvements

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @booc0mtaco has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
*Recommend*: merging this is _without_ squashing so that we preserve the commit messages which will be used in the version information on the next semantic releases.

**Comment by booc0mtaco** [comment]
Screen Shot 2019-12-31 at 12 50 38 PM

Screen Shot 2019-12-31 at 12 50 59 PM

**Comment by booc0mtaco** [comment]
Splitting into 

- #1815 
- #1816
- #1817

**Pull request closed without merging**
