### PR TITLE
Revert "fix(textinputwithcopybutton): clicks on URL within USM should…

### PR DESCRIPTION
**Pull request by il10**
… select all (#1926)"

This reverts commit 39deef90d6e7a7fbdef59a639d61f5675fa33783.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @il10 has signed the CLA. Thanks for the pull request!

**Comment by mxiao6** [comment]
You may want to change the title to `fix(textinputwithcopybutton): Revet clicks on URL within USM should select all`

**Comment by booc0mtaco** [comment]
@mxiao6 @il10 when the title has problems, you have to amend the commit and force-push. changing the description in github isn't sufficient in several cases; best to edit the PR

**Comment by mxiao6** [comment]
> @mxiao6 @il10 when the title has problems, you have to amend the commit and force-push. changing the description in github isn't sufficient in several cases; best to edit the PR

@booc0mtaco Understood. Moving forward instead of simply advising, I will directly review as change of request.

**Pull request merged**
