### PR TITLE
feat(uploader): prevent upload based on file size

### PR DESCRIPTION
**Pull request by priyajeet**
Rough

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @priyajeet has signed the CLA. Thanks for the pull request!

**Comment by ConradJChan** [comment]
`STATUS_CRITICAL` is a new error status that cannot be retried? Do we need to update the logic to be able to click to remove such files from the upload queue?

**Comment by jeremypress** [comment]
for restrictions like this, file type etc. customers are probably going to want custom error messages. Ideally we could provide that without provide a prop for each string.

**Comment by priyajeet** [comment]
Will have to make the error stuff default to string message if code is not provided or is bogus. And if no message either then we show our default message.

In either case onBeforeUpload should return data or promise and we should handle both, and the item returned can have the error info, which is then used to create the upload item object

**Pull request closed without merging**
