### PR TITLE
feat(access-label): Add text override prop

### PR DESCRIPTION
**Pull request by cweeii**
This change is to allow for passing in custom override message

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @cweeii has signed the CLA. Thanks for the pull request!

**Comment by booc0mtaco** [comment]
Hm, this component seems pretty simple. why not do a switch where it is used to either use `AccessLabel` or a component based on whatever condition sets the override?

**Comment by booc0mtaco** [comment]
extra note: have a look at `SharedLinkAccessDescription` which appears to need some similar treatment

**Comment by cweeii** [comment]
Thanks for the feedback.  Let me look at an alternative way of doing it.

**Pull request closed without merging**
