### PR TITLE
Update README.md

### LINKED ISSUE #905: Modify README
Availability of Box UI elements should be independent of its features.

"They can be used to navigate through, upload, preview, and select content stored on Box and are available both as React components and framework-agnostic JavaScript libraries."

### PR DESCRIPTION
**Pull request by Three7Six**
fix: Readability of readme

fixes #905 
Separate features and availability into two sentences. Removed occurrences of passive voice

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @Three7Six, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by Three7Six** [comment]
CLA signed

**Comment by jstoffan** [comment]
@Three7Six, can you update your commit message to follow the format described in [CONTRIBUTING.md](https://github.com/box/box-ui-elements/blob/master/CONTRIBUTING.md#step-4-push-your-feature-branch-to-your-fork)?

**Comment by CrispyMandollass** [comment]
CLA signed

**Pull request closed without merging**
