### PR TITLE
feat(changelog): Add CHANGELOG.md and changelog generation package.

### PR DESCRIPTION
**Pull request by stevegcoder**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @stevegcoder has signed the CLA. Thanks for the pull request!

**Comment by stevegcoder** [comment]
This is a Work in Progress.

**Comment by priyajeet** [comment]
Why is this needed? You can see the changelog under the releases tab. Is this needed for something else?

**Comment by booc0mtaco** [comment]
Agree with @priyajeet . We have the auto-generated changelog in GitHub already, and there's an API to pull that description as [`body`](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name). If this is needed for scripting, would it be possible to use the API instead? that way the changelog info would never diverge. Also, since `tag_name` is stable, that may be enough to get the proper `body` content, which would be the changelog in this case.

**Pull request closed without merging**
